<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DimesionsAndMultipliersSeeder extends Seeder
{
 /**
  * Run the database seeds.
  */
 public function run(): void
 {

  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '50x90',
   'width'                            => 50,
   'height'                           => 90,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 24,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 400,
   'large_format_sheet_area'          => 0.2,
   'large_format_multiplier'          => 35,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 440,
   'large_format_cut_to_sheet_area'   => 0.22,
   'large_format_cut_to_multiplier'   => 32,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '85x55',
   'width'                            => 55,
   'height'                           => 85,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 21,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 400,
   'large_format_sheet_area'          => 0.2,
   'large_format_multiplier'          => 30,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 400,
   'large_format_cut_to_sheet_area'   => 0.2,
   'large_format_cut_to_multiplier'   => 30,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '50x50',
   'width'                            => 50,
   'height'                           => 50,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 0,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 350,
   'large_format_sheet_area'          => 0.175,
   'large_format_multiplier'          => 54,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 340,
   'large_format_cut_to_sheet_area'   => 0.17,
   'large_format_cut_to_multiplier'   => 40,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '70x70',
   'width'                            => 70,
   'height'                           => 70,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 1,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 380,
   'large_format_sheet_area'          => 0.19,
   'large_format_multiplier'          => 30,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 360,
   'large_format_cut_to_sheet_area'   => 0.18,
   'large_format_cut_to_multiplier'   => 24,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '80x80',
   'width'                            => 80,
   'height'                           => 80,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 1,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 360,
   'large_format_sheet_area'          => 0.18,
   'large_format_multiplier'          => 24,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 400,
   'large_format_cut_to_sheet_area'   => 0.2,
   'large_format_cut_to_multiplier'   => 20,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '100x100',
   'width'                            => 100,
   'height'                           => 100,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 12,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 330,
   'large_format_sheet_area'          => 0.165,
   'large_format_multiplier'          => 12,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 360,
   'large_format_cut_to_sheet_area'   => 0.18,
   'large_format_cut_to_multiplier'   => 12,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => '150x150',
   'width'                            => 150,
   'height'                           => 150,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 4,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 330,
   'large_format_sheet_area'          => 0.165,
   'large_format_multiplier'          => 6,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 360,
   'large_format_cut_to_sheet_area'   => 0.18,
   'large_format_cut_to_multiplier'   => 6,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => 'A7',
   'width'                            => 74,
   'height'                           => 105,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 12,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 350,
   'large_format_sheet_area'          => 0.175,
   'large_format_multiplier'          => 18,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 360,
   'large_format_cut_to_sheet_area'   => 0.18,
   'large_format_cut_to_multiplier'   => 16,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => 'A6',
   'width'                            => 105,
   'height'                           => 148,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 8,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 350,
   'large_format_sheet_area'          => 0.175,
   'large_format_multiplier'          => 9,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 380,
   'large_format_cut_to_sheet_area'   => 0.19,
   'large_format_cut_to_multiplier'   => 9,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => 'A5',
   'width'                            => 148,
   'height'                           => 210,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 4,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 450,
   'large_format_sheet_area'          => 0.225,
   'large_format_multiplier'          => 6,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 470,
   'large_format_cut_to_sheet_area'   => 0.235,
   'large_format_cut_to_multiplier'   => 6,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => 'A4',
   'width'                            => 210,
   'height'                           => 297,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 2,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 320,
   'large_format_sheet_area'          => 0.16,
   'large_format_multiplier'          => 2,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 360,
   'large_format_cut_to_sheet_area'   => 0.16,
   'large_format_cut_to_multiplier'   => 2,
   'large_format_sheet_set'           => 2,
  ]);
  DB::table('dimensions_with_multipliers')->insert([
   'created_at'                       => now(),
   'updated_at'                       => now(),
   'name'                             => 'A3',
   'width'                            => 297,
   'height'                           => 420,
   'small_format_sheet_width'         => 320,
   'small_format_sheet_height'        => 450,
   'small_format_multiplier'          => 1,
   'small_format_sheet_set'           => 1,
   'large_format_sheet_width'         => 500,
   'large_format_sheet_height'        => 320,
   'large_format_sheet_area'          => 0.16,
   'large_format_multiplier'          => 1,
   'large_format_cut_to_sheet_width'  => 500,
   'large_format_cut_to_sheet_height' => 320,
   'large_format_cut_to_sheet_area'   => 0.16,
   'large_format_cut_to_multiplier'   => 1,
   'large_format_sheet_set'           => 2,
  ]);

 }
}
